### PR TITLE
Update tinder.py

### PR DESCRIPTION
**Pull request by mathowl**
open json with encoding utf8

### CODE REVIEW

**Comment by fsoubelet** [comment]
Well, I didn't expect to ever see a PR on this repo! Thanks for the contribution. Could you up the package version to `0.4.1` before we merge? This way I could make it a patch release.

**Comment by mathowl** [comment]
Sorry I am still a beginner at this. So you mean set tag release to 0.4.1 and include updated binaries?

**Comment by fsoubelet** [comment]
No worries. Just updating line 3 in `pyproject.toml` to read `version = "0.4.1"` will do it :)

**Comment by mathowl** [comment]
okidoki

**Pull request merged**
